name: Nightly Release

permissions:
  contents: read

on:
  push:
    branches:
      - main

jobs:
  nightly:
    uses: Checkmarx/ast-cli-javascript-wrapper-runtime-cli/.github/workflows/release.yml@main
    secrets: inherit