name: Nightly Release

permissions:
  contents: read

on:
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

jobs:
  nightly:
    uses: Checkmarx/ast-cli-javascript-wrapper-runtime-cli/.github/workflows/release.yml@main # zizmor: ignore[unpinned-uses]
    secrets: inherit # zizmor: ignore[secrets-inherit]